services:
  whatsapp-bot:
    container_name: whatsapp-bot-service
    build: 
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    
    env_file:
      - .env
      
    volumes:
      - wwebjs_auth:/app/.wwebjs_auth      # Volume nomeado
      - wwebjs_cache:/app/.wwebjs_cache    # Volume nomeado
      - ./cobrancas.json:/app/cobrancas.json
      
    ports:
      - "3000:3000"
      
volumes:
  wwebjs_auth:
  wwebjs_cache:
  
networks:
  rede_compartilhada:
    name: apiWhatsapp
    external: true